### ISSUE TITLE
Static file server does not correctly resolve directories containing index.html on Windows

### ISSUE THREAD

**Issue by willemolding** [stephank/hyper-staticfile#12]
This bug applies to Windows operating system only and can be replicated using the doc server example app.

Steps to reproduce:

- Start server by running `cargo doc && cargo run --example doc_server`
- Navigate to http://localhost:3000/hyper_staticfile/` in the browser (tested with Firefox). Server will respond with 403 Forbidden
- Instead navigate to http://localhost:3000/hyper_staticfile/index.html`. Page loads correctly

Presumably this is due to `open_with_metadata` returning an Err on windows when it is resolving the index.html

**Comment by stephank** [comment]
Thanks for catching this!

I don't have a Windows box handy, but can see about setting up a VM if you're also unable. I guess, looking at the code, what looks most suspicious is that we do `File::open` on the directory itself. Possibly that's not allowed on all platforms?

**Comment by Mxkkxa** [comment]
Thank you as well, I was going crazy wondering why it just doesn't work. Now using fix-windows branch in my .toml file and that fixed.
