### ISSUE TITLE
command line interface for hyper-staticfile

### ISSUE THREAD

**Issue by florianjacob** [stephank/hyper-staticfile#2]
@stephank Is a command line interface for hyper-staticfile already developed somewhere?
A small command line tool that serves the current directory via HTTP, like a replacement for `python -m http.server`?
If not I'll create such a project, I just want to make sure I didn't miss it and end up with two.

I developed something like that already directly on top of hyper back in the synchronous days. I now wanted to rewrite it for async hyper, had no idea how to feed files into tokio through hyper, but luckily I found this crate. 😉

**Comment by stephank** [comment]
Nope, not yet! Feel free to build one. 😃

**Comment by florianjacob** [comment]
@stephank thanks, I'll return! 🙂
