### ISSUE TITLE
Header Last-Modified should be in GMT instead of local time

### ISSUE THREAD

**Issue by misos1** [stephank/hyper-staticfile#29]
[Last-Modified](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Last-Modified)

But I am getting header like this:
```
last-modified: Tue, 21 Apr 2020 21:32:30 +0200
```

https://github.com/stephank/hyper-staticfile/blob/ea9805f86ad91621b4d01feed06c36b8407486e5/src/util/file_response_builder.rs#L101-L115

**Comment by stephank** [comment]
Oh! Good catch! 😅
