### ISSUE TITLE
Resolve url paths without trailing '/' to corresponding directory with index.html 

### ISSUE THREAD

**Issue by appcypher** [stephank/hyper-staticfile#33]
###  Actual behavior
When you request a path `/dashboard` and a corresponding `{root}/dashboard/index.html` file exists, the resolver returns a `ResolveResult::IsDirectory` variant which is essentially an error. 

It works when you add a trailing slash to the url path, that is `/dashboard/`, but the user may not be aware of this and it becomes annoying after a while.

For context, my frontend is developed with svelte-kit and in production static ssr build, it maps each route to separate directories containing index.html files. If one of those directories is `{root}/profile`, it would be nice if users that visit  `mysite.com/profile` would get the expected result.

The behavior is a result of an assumption made here.

https://github.com/stephank/hyper-staticfile/blob/85eee8d8ef2b5cbdbc032e77358e50d5201f25c1/src/util/requested_path.rs#L35-L46

##

### Expected behavior

The expected behavior is to return `ResolveResult::Found` when there is a corresponding directory with index.html and construct a response for it. 

##

### Reproduction

Add a new directory with an index.html file to your server root and try navigating to it without the trailing slash.

**Comment by stephank** [comment]
The intention is that an `IsDirectory` result should cause a (permanent) redirect to `/dashboard/`, in your case. The redirect imitates default behaviour of common webservers like apache or nginx. The redirect is implemented in `ResponseBuilder`, but I guess you're bypassing this and using something custom?

**Comment by appcypher** [comment]
That's right. I'm handling it as an error.

```rs
let result = hyper_staticfile::resolve(&root, &request)
    .await
    .map_err(|err| HandlerError::Internal { ... })?;

match result {
    ResolveResult::MethodNotMatched => Err(HandlerError::Client { ... }),
    ResolveResult::UriNotMatched => Err(HandlerError::Client { ... }),
    ResolveResult::NotFound => Err(HandlerError::Client { ... }),
    ResolveResult::PermissionDenied => Err(HandlerError::Client { ...}),
    ResolveResult::IsDirectory => Err(HandlerError::Client { ... }),
    ResolveResult::Found(_, _, _) => Ok(hyper_staticfile::ResponseBuilder::new()
        .request(&request)
        .build(result)
        .unwrap()),
}
```

Are you suggesting that it should be done this way instead?

```rs
match result {
    ResolveResult::MethodNotMatched => Err(HandlerError::Client { ... }),
    ResolveResult::UriNotMatched => Err(HandlerError::Client { ... }),
    ResolveResult::NotFound => Err(HandlerError::Client { ... }),
    ResolveResult::PermissionDenied => Err(HandlerError::Client { ...}),
    _ => Ok(hyper_staticfile::ResponseBuilder::new()
        .request(&request)
        .build(result)
        .unwrap()),
}
```

**Comment by stephank** [comment]
That should work, yes.

Maybe this is a docs issue for `ResolveResult`? It could be a bit more clear about what the default behaviour for each variant is.
