### ISSUE TITLE
Accessing arbitrary files

### ISSUE THREAD

**Issue by jannik4** [stephank/hyper-staticfile#35]
On windows it is possible to access arbitrary files from other drives than the server is started from.

For example, if the server is started from `D:\...`, you can get files from `C:` by requests like this: http://127.0.0.1/anypath/c:/windows/win.ini

This is the same bug as found here: https://github.com/tower-rs/tower-http/pull/204

**Comment by stephank** [comment]
I released 0.9.2 and 1.0.0-alpha.2 fixing this. Looking into an advisory. Thanks for reporting!
