### ISSUE TITLE
Set Travis CI to build master weekly.

### ISSUE THREAD

**Issue by nelsonjchen** [stephank/hyper-staticfile#4]
Tokio is a bit of a moving target. It's good to get a heads up on incompatiblity. Without #3, master currently does not build as it does not allow use of deprecated elements. Yet the badge is green as of this moment. The denial of deprecated elements declaration in this crate would be stronger by [enabling the cron job functionality in Travis CI](https://docs.travis-ci.com/user/cron-jobs/).

Please look into enabling this.

**Comment by stephank** [comment]
Thanks for pointing this out! Didn't even know it was possible. It's now enabled. :)
