### ISSUE TITLE
Question from beginning rustacean about the MainService in the example code.

### ISSUE THREAD

**Issue by najamelan** [stephank/hyper-staticfile#6]
https://github.com/stephank/hyper-staticfile/blob/554215012b589288750406362527b6e94d5464b7/examples/doc_server.rs#L60

I try to figure out how to use hyper properly, so thanks for the example code. I'm wondering about the service being instantiated for each new connexion. Would this be a recommended workflow or is it just to simplify the example. 

Should production code reuse service objects?

Sorry if this spams your issues ;(

**Comment by stephank** [comment]
Sorry for not getting back to you earlier! Think I'm not getting the GitHub notifications.

Creating a new service instance is definitely what I've been doing up until now, but I'm also not sure what changes are coming to Tokio 0.2.
